puitems = {
    'white-flower' : {'chance': 1000},
    'ant' : {'chance': 1000},
    'stick' : {'chance': 1000},
    'rock' : {'chance': 1000},
    'blade of grass' : {'chance': 1000},
    'leaf' : {'chance': 1000},
    'pebble' : {'chance': 900},
    'acorn' : {'chance': 900},
    'piece of dirt' : {'chance': 900},
    'blue-flower' : {'chance': 900},    
    'cheese' : {'chance': 850},        
    'frog' : {'chance': 800},
    'bird' : {'chance': 800},
    'red-flower' : {'chance': 800},        
    'squirrel' : {'chance': 700},
    'McDonald\'s' : {'chance': 700},
    'green-flower' : {'chance': 700},        
    'fat squirrel' : {'chance': 600},
    'litter' : {'chance': 600},
    'first edition charizard card' : {'chance': 600},
    'purple-flower' : {'chance': 700},            
    'bee hive' : {'chance': 500},
    'wasp hive' : {'chance': 500},
    'horent hive' : {'chance': 500},
    'mud wasp hive' : {'chance': 500},
    'barrel of toxic sludge' : {'chance': 500},
    'black-flower' : {'chance': 500},         
    'someone\'s dog' : {'chance': 400},
    'someone\'s cat' : {'chance': 400},
    'child\'s birthday gift' : {'chance': 400},
    'pink-flower' : {'chance': 400},        
    'very fat squirrel' : {'chance': 300},    
    'cardboard' : {'chance': 300},
    'raw salmon' : {'chance': 300},
    'dual heavy machine gun' : {'chance': 300},       
    'squirrel plush' : {'chance': 300},
    'yellow-flower' : {'chance': 300},     
    'scrap metal' : {'chance': 250},
    'abnormal pill' : {'chance': 200},   
    'cool stick' : {'chance': 200},
    'right airpod' : {'chance': 200},
    'arrow' : {'chance': 200},    
    'paper crane' : {'chance': 200},
    'sawdust' : {'chance': 200},
    'orange-flower' : {'chance': 200},     
    '200microgram piece of gold' : {'chance': 100},       
    'penny' : {'chance': 100},
    'rope' : {'chance': 100},
    'strawberry' : {'chance': 100},
    'apple' : {'chance': 100},
    'banna' : {'chance': 100},
    'orange' : {'chance': 100}, 
    'blueberry' : {'chance': 100}, 
    'carrot' : {'chance': 100},
    'lemon' : {'chance': 100},
    'raspberry' : {'chance': 100},
    'three-leafed clover' : {'chance': 100},
    'anthill' : {'chance': 100},            
    'umbrella' :{'chance' : 100},
    'extra extra large brik cola' :{'chance' : 100}, 
    'lame stick' :{'chance' : 100},        
    'chunk of asphalt' :{'chance' : 100},
    'nickel' : {'chance': 90},
    'rubber duck' : {'chance': 90},
    'rubik’s cube' : {'chance': 90},
    'rubik’s clock' : {'chance': 90},
    'cooler stick' : {'chance': 50},
    'spider-man movie' : {'chance' : 50},
    'prezel' : {'chance': 50},
    'fake plant' : {'chance': 50},
    'goblet' : {'chance' : 50},
    'lock of hair' : {'chance': 50},
    'airpod case' : {'chance': 50},
    'spider' : {'chance': 50},
    'cinnamon prezel' : {'chance': 40},
    'vanilla prezel' : {'chance': 40},                               
    'dagger with blood on it inscribed with the words \"TAROE SIMIL TAMONIN\"' : {'chance': 50},
    'book bound in flesh inscribed with the words \"SAROE TAMAL TAMOHAH\"' : {'chance': 50},    
    'rainbow-flower' : {'chance': 50},
    'fursuit head' : {'chance' : 25},
    'fursuit right arm' : {'chance' : 25},
    'fursuit left arm' : {'chance' : 25},
    'fursuit right leg' : {'chance' : 25},
    'fursuit left leg' : {'chance' : 25},
    'human brain' : {'chance' : 25},
    'can of door hinge oil' : {'chance' : 25},
    'script to family guy season 1 episode 1' : {'chance' : 10},   
    'four-leafed clover' : {'chance': 10},
    'a hard drive containing 1 bkc' : {'chance': 10},
    'Wendy\'s' : {'chance': 10},
    'Taco Bell' : {'chance': 10},
    'Burger King' : {'chance': 10},
    'brick with letter reading “i hate you samantha, you cheating piece of garbage”' : {'chance': 10},       
    'five-leafed clover' : {'chance': 9},         
    'nuclear bomb' : {'chance': 5},
    'normal pill' : {'chance': 5},
    'copy of Cheesy Brik the Movie' : {'chance' : 4},    
    'left airpod' : {'chance': 1},    
    'giant monster of a squirrel so fat it absorbs all it touches' : {'chance': 1}  
}
